### ISSUE TITLE
Hue Sync Box integration fails after HA 2025.11 update – 'ConfigEntry' object has no attribute 'runtime_data'

### ISSUE THREAD

**Issue by nickv1091** [mvdwetering/huesyncbox#152]
After updating Home Assistant Core to 2025.11.x, the Hue Sync Box custom integration no longer loads.

Error in log:
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'
File: custom_components/huesyncbox/services.py, line 107

This happens on every call to huesyncbox.set_sync_state and causes HA soft restarts.
Disabling the integration immediately stops the loop.

Environment:
- Home Assistant Core 2025.11.x
- Supervisor 2025.11.x
- Operating System 13.2
- Integration installed via HACS (latest release at time of writing)

Expected:
Integration should handle updated ConfigEntry structure introduced in HA 2025.11 and not crash when runtime_data is missing.

Temporary workaround:
Disabling or removing the integration stops restarts. All other core and custom components run normally.

**Comment by nickv1091** [comment]
Here is the automation I run. Sorry if my bug didn't make sense, I am still learning a bit. Happy to send anything else over. 

alias: (Live) Capitals Score Celebration with Video and Lights
description: ""
triggers:
  - entity_id:
      - sensor.capitals_game
    trigger: state
conditions:
  - condition: template
    value_template: >
      {% set capitals_id = 15 %} {{ (trigger.to_state.attributes.away_id ==
      capitals_id and
          (trigger.to_state.attributes.away_score | int) > (trigger.from_state.attributes.away_score | int)) or
         (trigger.to_state.attributes.home_id == capitals_id and
          (trigger.to_state.attributes.home_score | int) > (trigger.from_state.attributes.home_score | int)) }}
  - condition: state
    entity_id: input_boolean.hockey_mode
    state: "on"
actions:
  - parallel:
      - action: huesyncbox.set_sync_state
        metadata: {}
        data:
          sync: false
        target:
          device_id: f138c0c079de234b7da1782d66a134bd
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ range(0, 2) | random == 0 }}"
            sequence:
              - action: media_player.play_media
                target:
                  entity_id:
                    - media_player.tv_1
                    - media_player.tv_2
                data:
                  media:
                    media_content_id: http://192.168.5.57:8123/media/local/score.mp4
                    media_content_type: video
                    metadata: {}
          - conditions: []
            sequence:
              - action: media_player.play_media
                target:
                  entity_id:
                    - media_player.tv_1
                    - media_player.tv_2
                data:
                  media:
                    media_content_id: media-source://media_source/local/Capitals 25 goal.mp4
                    media_content_type: video
                    metadata: {}
      - sequence:
          - target:
              entity_id:
                - light.hue_bloom_1
                - light.hue_bloom_2
                - light.play_light_1
                - light.undercabinet_lights
                - light.undercabinet_lights_2
                - light.play_light_2
                - light.play_light_3
                - light.play_light_4
                - light.hue_lightstrip_1
                - light.hue_play_gradient_lightstrip_1
                - light.hue_lightstrip_1_2
                - light.hue_lightstrip_1_3
                - light.chair
                - light.h7021
                - light.hue_lightstrip_1_4
                - light.nico_desk
            data:
              brightness: 255
              rgb_color:
                - 255
                - 0
                - 0
            action: light.turn_on
      - target:
          entity_id: media_player.office
        data:
          volume_level: 0.65
        action: media_player.volume_set
      - - action: media_player.play_media
          target:
            entity_id: media_player.office
          data:
            media:
              media_content_id: |-
                {% set clips = [
                  "http://192.168.5.57:8123/local/Goal_Horn.mp3",
                  "media-source://media_source/local/Capitals 25 goal.mp3"
                ] %} {{ clips | random }}
              media_content_type: music
      - sequence:
          - target:
              entity_id: switch.shelly1minig3_cc8da2440908_switch_0
            action: switch.turn_on
            data: {}
          - target:
              entity_id: switch.fog_machine_initiation_switch_0
            action: switch.turn_on
            data: {}
          - target:
              entity_id:
                - switch.shelly1minig3_cc8da243dd04
            action: switch.turn_on
            data: {}
      - action: script.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: script.laser_18_lightning_repeat
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - parallel:
      - target:
          entity_id: switch.fog_machine_initiation_switch_0
        action: switch.turn_off
        data: {}
      - target:
          entity_id:
            - switch.shelly1minig3_cc8da243dd04
        action: switch.turn_off
        data: {}
      - target:
          entity_id: light.strobe_light_1
        action: light.turn_on
        data: {}
  - repeat:
      count: 4
      sequence:
        - target:
            entity_id:
              - light.hue_bloom_1
              - light.hue_bloom_2
              - light.hue_color_light_1
              - light.play_light_2
              - light.play_light_3
              - light.hue_lightstrip_1
              - light.hue_play_gradient_lightstrip_1
              - light.hue_lightstrip_1_2
              - light.hue_lightstrip_1_3
              - light.chair
              - light.h7021
              - light.hue_lightstrip_1_4
              - light.play_light_4
              - light.play_light_1
          action: light.turn_on
          data: {}
        - target:
            entity_id:
              - light.hue_bloom_1
              - light.hue_bloom_2
              - light.hue_color_light_1
              - light.play_light_2
              - light.play_light_3
              - light.hue_lightstrip_1_2
              - light.hue_lightstrip_1_3
              - light.chair
              - light.h7021
              - light.hue_lightstrip_1_4
              - light.play_light_1
              - light.play_light_4
              - light.nico_desk
          action: light.turn_off
          data: {}
        - delay: "00:00:00.7"
  - target:
      entity_id:
        - light.hue_bloom_1
        - light.hue_bloom_2
        - light.play_light_1
        - light.undercabinet_lights
        - light.undercabinet_lights_2
        - light.play_light_2
        - light.play_light_3
        - light.play_light_4
        - light.strobe_light_1
        - light.hue_lightstrip_1
        - light.hue_play_gradient_lightstrip_1
        - light.hue_lightstrip_1_2
        - light.hue_lightstrip_1_3
        - light.chair
        - light.h7021
        - light.hue_lightstrip_1_4
    action: light.turn_off
    data: {}
  - delay: "00:00:00.5"
  - parallel:
      - target:
          entity_id: switch.shelly1minig3_cc8da2440908_switch_0
        action: switch.turn_off
        data: {}
      - target:
          entity_id: switch.fog_machine_initiation_switch_0
        action: switch.turn_off
        data: {}
      - action: huesyncbox.set_sync_state
        metadata: {}
        data:
          sync: true
        target:
          device_id: f138c0c079de234b7da1782d66a134bd
      - action: automation.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: automation.side_tv_displays
      - action: automation.trigger
        metadata: {}
        data:
          skip_condition: true
        target:
          entity_id: automation.side_tv_displays
      - target:
          entity_id:
            - switch.shelly1minig3_cc8da243dd04
        action: switch.turn_off
        data: {}

On Sat, Nov 8, 2025 at 1:49 PM Michel van de Wetering <notifications@github.com> wrote:

mvdwetering
 left a comment 
[(mvdwetering/huesyncbox#152)](https://github.com/mvdwetering/huesyncbox/issues/152#issuecomment-3506796831)
Not sure what ConfigEntry structure change you are referring to in the Expected section? As far as I can tell there have been no changes around the runtime_data part recently. Every ConfigEntry must have a runtime_data attribute.

I tried to reproduce this locally, but I have not been able to get this error (there is a warning about the deprecated hass parameter, but that will only start failing in 2026.10)

Could you share the exact set_sync_state call you are doing?

**Comment by mvdwetering** [comment]
In the `huesyncbox.set_sync_state` call you specified a device as target. There was an announcement that it would be deprecated, but as far as I understood it should still work for coming year until 2026.11 release.

But as an experiment can you try changing the target to an entity (any entity offered by HueSyncBox integration) and see if that fixes it?

Alternatively, because you are only controlling one setting, you could use the `turn_on` and `turn_off` services on the light sync switch entity like you do for the Shelly entities in your automation.

**Comment by nickv1091** [comment]
Will test as an entity and report back!

**Comment by nickv1091** [comment]
When called as an entity, no issue or errors. When call as shown above;

Logger: homeassistant.helpers.service
Source: helpers/deprecation.py:257
First occurred: 5:46:48 PM (1 occurrence)
Last logged: 5:46:48 PM

The deprecated argument hass was passed to async_extract_config_entry_ids from huesyncbox. It will be removed in HA Core 2026.10. Use async_extract_config_entry_ids without hass argument instead, please create a bug report at https://github.com/mvdwetering/huesyncbox/issues

**Comment by mvdwetering** [comment]
Closing this as it was solved. The deprecation warning was already reported in #150 and will be tracked there.
